### ISSUE TITLE
The slider twitches when you scroll back

### ISSUE THREAD

**Issue by Extnow** [dmitrymorozoff/react-circle-slider#2]
Hey, thanks for the great plugin.

Faced the problem: when maximum values are low, for example 6 and step is 1. When you scroll back, the slider starts to twitch due to the fact that it is rolled back to the position of the previous value on the slider too.

Thanks for your help.

**Comment by dmitrymorozoff** [comment]
Привет. Создай пожалуйста issue на гитхабе, чтобы я не забыл. Поправлю как будет время.

**Comment by Extnow** [comment]
Привет, спасибо за отклик!
Ишью создал, надеюсь, что понятно описал проблему

**Comment by dmitrymorozoff** [comment]
@Extnow I updated the library, can you please try with recent version and check if this issue exists
