### ISSUE TITLE
Disabled attribute does not work.

### ISSUE THREAD

**Issue by AKosorukov** [dmitrymorozoff/react-circle-slider#3]
Disabled attribute does not work!

Take your example, set "npm i react-circle-slider - save", open the file "example\index.tsx" and change the import {CircleSlider} from "../src/circle-slider"; on import {CircleSlider} from "react-circle-slider"; et voila: disabled attribute does not block rotation.

**Comment by dmitrymorozoff** [comment]
Hi @AKosorukov. I can not reproduce the bug. Please give us more detailed explanation.
