### ISSUE TITLE
Set the color of progressColor with gradient

### ISSUE THREAD

**Issue by Extnow** [dmitrymorozoff/react-circle-slider#5]
Hi, can you add the functionality of color adjustment progressColor using gradient?

Thanks for your help.

**Comment by dmitrymorozoff** [comment]
@Extnow Yes of course. In the next update I will add this feature.

**Comment by itsmichaeldiego** [comment]
@dmitrymorozoff +1 on Extnow comment, I would really like this too!

**Comment by dmitrymorozoff** [comment]
@Extnow @itsmichaeldiego I updated the library, can you please try with latest version 1.5.1

**Comment by Extnow** [comment]
It would be great if the gradient was not from the bottom to the top, but showed the progress of achieving the highest value

**Comment by MahsaMaslahati** [comment]
Hello and thanks for the great component you provided. I agree with Extnow, It would be great if the gradient had a direction and we could set it from left to right, not from bottom to top, so it would show the progress of getting to the highest value.
I would really appreciate your time and  effort.
