### ISSUE TITLE
Error on Build Production 

### ISSUE THREAD

**Issue by khuznain** [dmitrymorozoff/react-circle-slider#8]
I got error on build production - in node_module/lib/index.. can you fixed this ?

**Comment by dmitrymorozoff** [comment]
@khuznain  I updated the library, can you please try with recent version and check if this issue exists

**Comment by khuznain** [comment]
Thanks man it build working now, but can you also fixed this ? 
1 - Warning: Invalid DOM property `stop-color`. Did you mean `stopColor`?
2 - if setting value - coming from api, value only set when max=101 else not working..
3 - some how it's not going from 99 if max value 100, sometime

**Comment by dmitrymorozoff** [comment]
@khuznain 
Of course. How will free time I will fix it

**Comment by khuznain** [comment]
Hi @dmitrymorozoff did you fixed these issue ? one more thing how will i display percentage % next right side of values ! is this lib has this feature or i will add this be my self !

**Comment by dmitrymorozoff** [comment]
Hi @khuznain . `showPercentage` prop added, package updated. Try it out!

_1 - Warning: Invalid DOM property stop-color. Did you mean stopColor?_ -> This bug is fixed.

Please add a more detailed description of other bugs.

**Comment by khuznain** [comment]
wow thanks man, now everything is working fine !
