### ISSUE TITLE
Can't set value to 100, work tell 99

### ISSUE THREAD

**Issue by khuznain** [dmitrymorozoff/react-circle-slider#9]
Hi i can 't set value to 100 by default only set value works tell 99, 
also 100 work if max is 101, can u fixed this please

```
<CircleSlider
        value={updatedValue ? updatedValue : 100}
        size={220}
        // min={0}
        // max={100}
        onChange={onChange}
        showPercentage={true}
        showTooltip={true}
        tooltipSize={36}
        gradientColorFrom="#617b9c"
        gradientColorTo="#c14380"
        tooltipColor="#c14380"
        progressColor="#c14380"
        knobColor="#ddd"
        shadow={false}
      />
```

**Comment by khuznain** [comment]
Hi i can 't set value to 100 by default only set value works tell 99

**Comment by khuznain** [comment]
Hi, any update regarding this issue, please we need changes asp .. we are going to use in production !

**Comment by dmitrymorozoff** [comment]
@khuznain I updated the library, can you please try with recent version and check if this issue exists

**Comment by khuznain** [comment]
Hi, it's working, thanks man ! You can close the issue now.
